#!/bin/sh

. /etc/init.d/functions

checkused(){
	SCRIPT=$1
	DEVNAME=`basename $2`
	DEVPATH=/dev/$DEVNAME
	SYSPATH=/sys/block/$DEVNAME

	if [ -b "$DEVPATH" ] && [ -d "$SYSPATH" ]; then
		for SUBNAME in $SYSPATH/$DEVNAME"?"
		do
			if [ -d "$SUBNAME" ]; then
				HOLDERS=$SUBNAME/holders
				if [ "`ls -A $HOLDERS`" -ne "" ]; then
					setlog "$SCRIPT" "$DEVNAME has been used by other" 1
					return 1
				fi
			fi
		done
		return 0
	else
		setlog "$SCRIPT" "$DEVNAME is not block device" 1
		return 1
	fi
}

killused(){
        if [ -z $1 ]; then
                echo parameter error
                return 1
        fi

        HOOK_PID=`fuser -m $1`
        HTTP_PID=`cat /var/log/nginx.pid`

        for proc in $HOOK_PID; do
                setlog "killused" "kill $proc" 0
                if [ $HTTP_PID"x" == $porc"x" ]; then
                        continue;
                fi
                kill $proc
        done

        HOOK_PID=`fuser -m $1`

        for proc in $HOOK_PID; do
                setlog "killused" "kill -9 $proc" 0
                if [ $HTTP_PID"x" == $porc"x" ]; then
                        echo skip base web service
                        continue;
                fi
                kill -9 $proc
        done

        return 0
}
