#!/bin/sh

. /etc/init.d/functions

mdada -As >> /var/log/migrate.log

if [ $? -ne 0 ]; then
	setlog `basename $0` "can't active raid device" 1
	exit 1
fi

if [ -b "/dev/md9" ]; then
	mdadm --assemble /dev/md9 \
		--name="userspace" --update=name \
		/dev/sd[a-z]1
fi

for id in `seq 0 9`
do
	if [ -b "/dev/md"$id ]
		mdadm --assemble $storspace \
			--name="storspace"$id --update=name \
			/dev/sd[a-z]2
	fi
done
