#!/bin/sh

. /etc/init.d/functions

keypath=/opt/etc/sshd
confile=/opt/etc/sshd/sshd_config
service=sshd
execute="sshd"
exeopts="-f $confile"

service_prepare(){
        if [ ! -d $keypath ]; then
                mkdir -p /var/data
        fi

        if [ ! -f $keypath/ssh_host_rsa_key ]; then
		ssh-keygen -t rsa1  -f $keypath/ssh_host_rsa_key   -N ''
	fi
        if [ ! -f $keypath/ssh_host_dsa_key ]; then
		ssh-keygen -t dsa   -f $keypath/ssh_host_dsa_key   -N ''
	fi
	if [ ! -f $keypath/ssh_host_ecdsa_key ]; then
		ssh-keygen -t ecdsa -f $keypath/ssh_host_ecdsa_key -N ''
	fi

	if [ ! -f $confile ]; then
		echo "UsePrivilegeSeparation no" > $confile
		echo "HostKey $keypath/ssh_host_rsa_key" >> $confile
		echo "HostKey $keypath/ssh_host_dsa_key" >> $confile
		echo "HostKey $keypath/ssh_host_ecdsa_key" >> $confile
	fi
}

service_start(){
        [ ! -d /var/empty ] && mkdir -p /var/empty

        service_prepare
        runprocess "$service" "$execute" "$exeopts"
}

service_stop(){
        stoprocess "$service" "$execute" "$exeopts"
}

case $1 in
        start)
                service_start
                exit 0 ;;
        stop)
                service_stop
                exit 0 ;;
        restart)
                service_restart
                exit 0 ;;
        status)
                service_status
                exit 0 ;;
        *)
                echo "Usage: `basename $0` {start|stop|restart|status}"
                exit 1 ;;
esac
