#!/bin/sh

. /etc/init.d/functions

confile=/etc/syslog.conf
service=crond
execute="/sbin/crond -S"

service_prepare(){
	[ ! -d /var/spool/cron/crontabs ] && mkdir -p /var/spool/cron/crontabs
}

service_start(){
        service_prepare
	runprocess $service $execute
}

service_stop(){
	stoprocess $service $execute
}

service_restart(){
	service_stop
	service_start		
}

case $1 in
        start)
                service_start
                exit 0 ;;
        stop)
                service_stop
                exit 0 ;;
        restart)
                service_restart
                exit 0 ;;
        status)
                service_status
                exit 0 ;;
        *)
                echo "Usage: `basename $0` {start|stop|restart|status}"
                exit 1 ;;
esac
