#!/bin/sh

. /etc/init.d/functions

keypath=/etc
confile=nginx/nginx.conf
service=nginx
execute="/sbin/nginx -p /var/ -c"

service_prepare(){
	[ ! -d /var/logs ] && mkdir -p /var/logs/

	if [ -d /opt/$confile ]; then
		confile=/opt/$confile
	else
		confile=/etc/$confile
	fi
}

service_start(){
        [ ! -d /var/empty ] && mkdir -p /var/empty

        service_prepare
        runprocess $service "$execute $confile"
}

service_stop(){
        stoprocess $service "$execute $confile"
}

case $1 in
        start)
                service_start
                exit 0 ;;
        stop)
                service_stop
                exit 0 ;;
        restart)
                service_restart
                exit 0 ;;
        status)
                service_status
                exit 0 ;;
        *)
                echo "Usage: `basename $0` {start|stop|restart|status}"
                exit 1 ;;
esac
