#!/bin/sh

. /etc/init.d/functions

BASENAME=`basename $0`
USERRAID=/dev/md/userspace
STORRAID=/dev/md/storspace

mdadm -As >> /var/log/mdinit.log

if [ -b $USERRAID ]; then
	[ ! -f /opt ] && mkdir -p /opt

	echo "mount $USERRAID"
	mount -t ext4 $USERRAID /opt
	if [ $? -ne 0 ]; then
		setlog $BASENAME "mount userspace failed..." 1
		exit 0
	else
		if [ -d /opt/etc/nasapp.d ]; then
			for optscript in /opt/etc/nasapp.d/S??*
			do
				$optscript >> /var/log/optinit.log 2>&1
			done
		fi

		if [ -d /opt/etc/init.d ]; then
			for optscript in /opt/etc/init.d/S??*
			do
				$optscript >> /var/log/optinit.log 2>&1
			done
		fi				
	fi
else
	setlog $BASENAME "userspace bootup failed..." 1
	exit 1
fi

for storspace in $STORRAID[0-16]
do
	if [ -b $storspace ]; then
		echo "mount $storspace"
		local mountpath=/mnt/`basename $storspace`
		mkdir -p $mountpath
		mount -t ext4 $storspace $mountpath
		if [ $? -ne 0 ]; then
			setlog $BASENAME "mount $storspace failed..." 1
		fi
	fi
done

exit 0
