#!/bin/sh

. /etc/init.d/functions

confile=/etc/udev/udev.conf
service=thttpd
execute="/sbin/thttpd"
exeopts="-u admin"

service_prepare(){
	return 0
}

service_start(){
        [ ! -d /var/run ] && mkdir -p /var/run

        service_prepare
	runprocess "$service" "$execute" "$exeopts"
}

service_stop(){
	stoprocess "$service" "$execute" "$exeopts"
}

service_restart(){
	service_stop
	service_start
}

case $1 in
        start)
                service_start
                exit 0 ;;
        stop)
                service_stop
                exit 0 ;;
        restart)
                service_restart
                exit 0 ;;
        status)
                service_status
                exit 0 ;;
        *)
                echo "Usage: `basename $0` {start|stop|restart|status}"
                exit 1 ;;
esac
