#!/bin/sh

. /etc/init.d/functions

confile=/etc/udev/udev.conf
service=udevd
execute="/sbin/udevd -d"

service_prepare(){
	if [ ! -d /run ]; then
		if [ -d /var/run ]; then
			ln -s /var/run /run
		else
			setlog udevd "can't link /var/run 2 /run"
			exit 1
		fi
	fi
}

service_start(){
        [ ! -d /var/run ] && mkdir -p /var/run

        service_prepare
        runprocess $service $execute

	udevadm_path="/sbin/udevadm"

	if [ -f $udevadm_path ]; then
		$udevadm_path trigger --action=add
	else
		setlog udevd "can't found udevadm in system" 1
	fi
}

service_stop(){
        stoprocess $service $execute
}

service_restart(){
	service_stop
	service_start
}

case $1 in
        start)
                service_start
                exit 0 ;;
        stop)
                service_stop
                exit 0 ;;
        restart)
                service_restart
                exit 0 ;;
        status)
                service_status
                exit 0 ;;
        *)
                echo "Usage: `basename $0` {start|stop|restart|status}"
                exit 1 ;;
esac
